# Generated by Django 2.1.2 on 2018-12-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todoLst', '0002_auto_20181210_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
