# Generated by Django 2.1.2 on 2018-12-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todoLst', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'in_progress'), (2, 'done')]),
        ),
    ]
